// Survey every list in real C3 project files, to write the merge profiles from data: for
// each file kind and list path, what the elements are, which keys could identify them
// (present in every element, unique within every list), and whether scalar lists hold
// unique or sorted values.
//   tsx scripts/profile-survey.ts <project dir | dir of projects>... > reports/profile-survey.md
import { readdir, stat } from "node:fs/promises";
import path from "node:path";
import { loadProject } from "../src/model/project.ts";

const ID_CANDIDATES = ["uid", "sid", "name", "id", "type", "title", "includeSheet", "effectId", "behaviorId", "functionName", "imageSpriteId"];

interface Stat {
  lists: number; nonEmpty: number; elements: number; types: Set<string>; files: Set<string>;
  keysAll: Set<string> | null; // keys present in every object element
  unique: Map<string, number>; // id candidate → lists where it's present on all and unique
  uniqueScalars: number; sortedScalars: number; scalarLists: number; // lists of ≥ 2 scalars
  example: string;
}
const stats = new Map<string, Stat>();
const kindOf = (rel: string) => rel.endsWith(".c3proj") ? "project" : rel.split("/")[0];
// Recursive structures (sub-events, sub-layers, subfolders) collapse to one pattern.
// Keys that are user names (effects, variables, behaviors, parameters) collapse to `*`.
const DYNAMIC = /\.(effects|instanceVariables|behaviors|parameters|properties)\.[^.[\]]+/g;
const norm = (p: string) => p.replace(DYNAMIC, ".$1.*").replace(/((\.[^.[\]]+\[\])+?)\1+/g, "$1");

function visit(kind: string, file: string, v: any, p: string) {
  if (Array.isArray(v)) {
    const key = `${kind} ${norm(`${p}[]`)}`;
    const s = stats.get(key) ?? {
      lists: 0, nonEmpty: 0, elements: 0, types: new Set(), files: new Set(), keysAll: null,
      unique: new Map(), uniqueScalars: 0, sortedScalars: 0, scalarLists: 0, example: "",
    };
    stats.set(key, s);
    s.lists++; s.files.add(file);
    if (v.length) s.nonEmpty++;
    s.elements += v.length;
    for (const e of v) s.types.add(Array.isArray(e) ? "array" : e === null ? "null" : typeof e);
    const objs = v.filter((e) => e && typeof e === "object" && !Array.isArray(e));
    if (objs.length && objs.length === v.length) {
      for (const o of objs) {
        const ks = new Set(Object.keys(o));
        s.keysAll = s.keysAll ? new Set([...s.keysAll].filter((k) => ks.has(k))) : ks;
      }
      for (const c of ID_CANDIDATES) {
        const vals = objs.map((o) => o[c]);
        if (vals.every((x) => x !== undefined) && new Set(vals.map((x) => JSON.stringify(x))).size === vals.length) {
          s.unique.set(c, (s.unique.get(c) ?? 0) + 1);
        }
      }
    }
    if (v.length >= 2 && v.every((e) => typeof e !== "object" || e === null)) {
      s.scalarLists++;
      if (new Set(v).size === v.length) s.uniqueScalars++;
      const strs = v.map(String);
      if (strs.every((x, i) => i === 0 || strs[i - 1].localeCompare(x, undefined, { sensitivity: "base", numeric: true }) <= 0)) s.sortedScalars++;
      if (!s.example) s.example = JSON.stringify(v.slice(0, 4)).slice(0, 80);
    }
    v.forEach((e) => visit(kind, file, e, `${p}[]`));
  } else if (v && typeof v === "object") {
    for (const [k, e] of Object.entries(v)) visit(kind, file, e, p ? `${p}.${k}` : k);
  }
}

async function projectsIn(dir: string): Promise<string[]> {
  const entries = await readdir(dir);
  if (entries.some((e) => e.endsWith(".c3proj"))) return [dir];
  const out: string[] = [];
  for (const e of entries) if ((await stat(path.join(dir, e))).isDirectory()) out.push(...(await projectsIn(path.join(dir, e)).catch(() => [])));
  return out;
}

let nProjects = 0, nFiles = 0;
for (const arg of process.argv.slice(2)) {
  for (const dir of await projectsIn(arg)) {
    const proj = await loadProject(dir).catch(() => null);
    if (!proj) continue;
    nProjects++;
    for (const [rel, f] of proj.files) {
      if (!f.json || rel.endsWith(".uistate.json") || rel.startsWith("files/") || rel.includes("/files/")) continue;
      if (!/\.c3proj$|^(eventSheets|layouts|objectTypes|families|timelines|flowcharts)\//.test(rel)) continue;
      nFiles++;
      visit(kindOf(rel), `${path.basename(dir)}/${rel}`, f.json, "");
    }
  }
}

console.log(`# Profile survey\n\n${nProjects} projects, ${nFiles} files. Generated by \`scripts/profile-survey.ts\`.\n`);
console.log("Columns: lists seen (non-empty) · elements · element types · keys in every element · id candidates (unique in N of the non-empty lists) · scalar lists: unique values / sorted.\n");
let lastKind = "";
const numeric = [...stats].filter(([, s]) => [...s.types].every((t) => t === "number")).length;
console.log(`${numeric} list paths hold only numbers (colours, vectors, sid lists): not shown, they merge as one value.`);
for (const [key, s] of [...stats].sort(([a], [b]) => a.localeCompare(b))) {
  if (s.types.size && [...s.types].every((t) => t === "number")) continue;
  const [kind, p] = key.split(" ");
  if (kind !== lastKind) { console.log(`\n## ${kind}\n\n| list | lists | elements | types | keys in all | id candidates | scalars unique / sorted |\n|---|---|---|---|---|---|---|`); lastKind = kind; }
  const ids = [...s.unique].map(([k, n]) => `${k} ${n}/${s.nonEmpty}`).join(", ");
  const keys = s.keysAll ? [...s.keysAll].slice(0, 8).join(" ") + (s.keysAll.size > 8 ? " …" : "") : "";
  const scal = s.scalarLists ? `${s.uniqueScalars}/${s.scalarLists} · ${s.sortedScalars}/${s.scalarLists} ${s.example}` : "";
  console.log(`| \`${p}\` | ${s.lists} (${s.nonEmpty}) | ${s.elements} | ${[...s.types].join(" ")} | ${keys} | ${ids} | ${scal.replace(/\|/g, "\\|")} |`);
}
